version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
  
  # chroma:
  #   image: ghcr.io/chroma-core/chroma:latest
  #   volumes:
  #     - chroma_index:/chroma/.chroma/index
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - IS_PERSISTENT=TRUE
  #     - ALLOW_RESET=TRUE

volumes:
  postgres_data:
  ollama:
  # chroma_index: